# Generated by Django 2.2.3 on 2019-08-01 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('mail_addr', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='note_id',
        ),
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_user', models.IntegerField(null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.BookInfo')),
                ('note_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Note')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.UserInfo'),
        ),
    ]
