# Generated by Django 2.2.3 on 2019-08-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190801_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='context',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
